name: CI
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
jobs:
  build:
    name: Run MATLAB checks and tests
    env:
      snapshot_version: v1.5.0
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v2
        with:
          products: >
            Mapping_Toolbox
            Image_Processing_Toolbox
            MATLAB_Coder
      - name: Cache snapshot data
        id: cache-snapshots
        uses: actions/cache@v4
        with:
          path: tests/snapshots/data
          key: snapshots-${{ env.snapshot_version }}
      - name: Download and extract snapshot data
        if: steps.cache-snapshots.outputs.cache-hit != 'true'
        working-directory: tests/snapshots
        shell: bash
        run: |
          curl -L -o snapshot_data.tar.gz \
          "https://github.com/TopoToolbox/snapshot_data/releases/download/$snapshot_version/snapshot_data.tar.gz"
          tar -xzf snapshot_data.tar.gz
      - name: Verify snapshot data
        working-directory: tests/snapshots
        shell: bash
        if: ${{ matrix.os != 'windows-latest' }}
        run:
          shasum -c --status sha256sum.txt
      - name: Run checks and tests
        uses: matlab-actions/run-build@v2
        with:
          tasks: compile check test
